[package]
name = "tafl"
version = "0.0.1-alpha.1"
authors = ["etandel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
