name: Publish

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish
      run: cargo publish --token $CARGO_TOKEN
      env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}

